### ISSUE TITLE
Recognise and highlight `txtar` extension

### ISSUE THREAD

**Issue by bitfield** [twpayne/vscode-testscript#1]
Thanks for this extension, @twpayne! Once rogpeppe/go-internal#159 is released (or even before), it would be great to have `vscode-testscript` recognise files with a `.txtar` extension as test scripts.

**Comment by twpayne** [comment]
Wow, I didn't realize this extension had users other than me!

Fixed with 29101fa4a30c4ed69f052b74c8a249039f3519b7, and I've published v0.0.3 which includes the change.

**Comment by bitfield** [comment]
Surely an all-time open source speed record for response to a feature request, thank you! 🔥 🥂
