### ISSUE TITLE
Support highlighting for embedded protobuf files

### ISSUE THREAD

**Issue by katexochen** [twpayne/vscode-testscript#2]
Hey, thanks for writing this extension, it works great!

Would be super nice to also have syntax highlighting for protobuf files (like done by https://github.com/zxh0/vscode-proto3) for embedded files, I'm working some CLI tool that interacts a lot with proto.

**Comment by twpayne** [comment]
OK, this is now done, and I've published v0.0.4 of the plugin to the VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=twpayne.vscode-testscript

**Comment by katexochen** [comment]
Thank you so much, works perfectly! :tada:
