### ISSUE TITLE
configurable file extensions

### ISSUE THREAD

**Issue by mark-pictor-csec** [twpayne/vscode-testscript#3]
I see that `v0.0.4` disabled highlighting for `*.txt`. This is actually the extension my team uses for testscript files.

I'm assuming you disabled this because txt is popular even outside of the testscript user circles.

Understandable, but it'd be nice to have a way to re-enable. Two solutions seem most obvious to me:
* add a config option to choose the allowed extension(s), or
* add a config option to ignore *.txt (or files in general?) unless inside a dir matching a particular pattern
  * some of ours live under a `script/` dir, others under `testdata/`

----

Unrelated, but seems too trivial for its own issue: SEO

I think I'd tried searching for `txtar` before, but didn't see your extension until noticing that `brody715.txtar` credits it. I assume there's a way to add keywords for vscode extension search. I'd suggest adding `txtar`, `go-internal/testscript`, and perhaps `rogpeppe`, to aid those looking for such an extension.

**Comment by twpayne** [comment]
As you say, including `.txt` as an extension means that this extension highlights all `.txt` files, including `.txt` files which are not testscripts.

There's no easy way to add a config option for this, as the extension is a static JSON file (a TextMate grammar) with no dynamic elements.

I'd recommend renaming your testscripts to use the `.txtar` extension.

Thanks for the tips on SEO. I've added some tags to the repo. Normally VSCode will propose this extension whenever it sees you opening a `.txtar` file, which is how I expect most users discover this plugin.

**Comment by mark-pictor-csec** [comment]
What's involved in getting a highlighter to show up in the "language mode" menu? That way I could switch to it manually.

Renaming all of the script tests is kind of a hassle when only part of the team uses vscode.

**Comment by twpayne** [comment]
> What's involved in getting a highlighter to show up in the "language mode" menu? That way I could switch to it manually.

I don't know. I wrote vscode-testscript for my own use, and it works fine for me.



> Renaming all of the script tests is kind of a hassle when only part of the team uses vscode.

It's one shell command and one line of code change.

I will consider a PR that implements the functionality you want, but will not work on this myself.

**Comment by mark-pictor-csec** [comment]
> I will consider a PR that implements the functionality you want, but will not work on this myself.

Cool, I'll keep it in mind for when I have a bit of time.

> It's one shell command and one line of code change.

Yes, per set of script tests - we have multiple 🙂 

Thanks for writing this extension!

**Comment by mark-pictor-csec** [comment]
it _is_ in the language mode menu... I was looking for "txtar", not "testscript" 🤦
